### ISSUE TITLE
Please help with editing the datapack

### ISSUE THREAD

**Issue by Dalan13** [Lettose/Ritualistic-Teleporters#2]
Hi. I wanted to use your datapack to play with the aether mod. But the following problem arose - you can't light candles in aether. Is there a way to use sea cucumbers as candles? How can I edit a datapack for this purpose?

**Comment by Lettose** [comment]
Hello! I made changes to v1.4 for you so rituals use sea pickles instead of candles. Here's the [download link](https://www.dropbox.com/scl/fi/1p6vzqzyzju0rqe9c8jtk/Ritualistic_Teleporters_v1.4_1.21.x_Augmented.zip?rlkey=n0l4f3gd7xjdsqac6zhco0asb&st=d5bwxb3k&dl=1).

If you need something other than sea pickles, you can modify the 'candles.json' file located here in the datapack: .\Ritualistic_Teleporters_v1.4_1.21.x_Augmented\data\minecraft\tags\block

You could probably use 'minecraft:air' if you only want the ritual block structure without anything in place of the candles.

This folder also has 'deepslate_blocks.json' and 'deepslate_slabs.json' which you can modify to use different blocks for the ritual structure if you want to use specific blocks from the aether mod for example.

Hope this helps!
